import type { GlossaryTerm } from "@/lib/domain/types";

const glossary = (
  id: string,
  term: string,
  definition: string,
  relatedHrefs: readonly string[],
): GlossaryTerm => ({ id, term, definition, relatedHrefs });

export const GLOSSARY_TERMS: readonly GlossaryTerm[] = [
  glossary(
    "digital-twin",
    "Digital Twin",
    "A computational representation of a physical asset and its relevant behavior.",
    ["/architecture", "/twin-capsule"],
  ),
  glossary(
    "digital-thread",
    "Digital Thread",
    "The connected information trace that follows an asset across its lifecycle.",
    ["/architecture"],
  ),
  glossary(
    "digital-triplet",
    "Digital Triplet",
    "A research direction combining a physical machine, a digital twin, and an AI Scientist.",
    ["/architecture", "/ai-scientist"],
  ),
  glossary(
    "twin-capsule",
    "Twin Capsule",
    "A bounded record of an asset, signals, features, failure modes, and provenance.",
    ["/twin-capsule"],
  ),
  glossary(
    "twin-registry",
    "Twin Registry",
    "A catalogue that identifies and locates Twin Capsules.",
    ["/twin-capsule"],
  ),
  glossary(
    "twin-lab",
    "Twin Lab",
    "An isolated environment for investigation on a digital representation rather than a physical machine.",
    ["/architecture", "/experiment-fabric"],
  ),
  glossary(
    "experiment-fabric",
    "Experiment Fabric",
    "The system that treats experiments, their configurations, and their evidence as first-class objects.",
    ["/experiment-fabric"],
  ),
  glossary(
    "feature-factory",
    "Feature Factory",
    "The transformation of raw industrial signals into engineered features.",
    ["/feature-factory"],
  ),
  glossary(
    "residual-intelligence",
    "Residual Intelligence",
    "Reasoning from the difference between physical measurement and digital-twin prediction.",
    ["/feature-factory"],
  ),
  glossary(
    "synthetic-fault",
    "Synthetic Fault",
    "A fault scenario generated by a model, rather than observed in an operating plant.",
    ["/fault-lab"],
  ),
  glossary(
    "fault-injection",
    "Fault Injection",
    "A controlled modification of a twin or input to study detection behavior.",
    ["/fault-lab"],
  ),
  glossary(
    "ai-scientist",
    "AI Scientist",
    "A reasoning and experimentation layer that remains outside the control loop.",
    ["/ai-scientist"],
  ),
  glossary(
    "fleet-intelligence",
    "Fleet Intelligence",
    "Cross-asset learning and validation that preserves engineering context.",
    ["/fleet-intelligence"],
  ),
  glossary(
    "physics-informed-ml",
    "Physics-Informed ML",
    "Machine learning constrained or informed by engineering relationships.",
    ["/feature-factory", "/algorithm-arena"],
  ),
  glossary(
    "gray-box-model",
    "Gray-box Model",
    "A hybrid model that combines physical structure with learned components.",
    ["/algorithm-arena"],
  ),
  glossary(
    "verification",
    "Verification",
    "Checking that an implementation conforms to its specified design.",
    ["/experiment-fabric"],
  ),
  glossary(
    "validation",
    "Validation",
    "Assessing whether a result is fit for its intended engineering decision.",
    ["/experiment-fabric"],
  ),
  glossary(
    "uncertainty-quantification",
    "Uncertainty Quantification",
    "Characterizing uncertainty that affects an inference or recommendation.",
    ["/experiment-fabric", "/research"],
  ),
  glossary(
    "model-provenance",
    "Model Provenance",
    "The reproducibility record for an asset, data, features, model, code, and configuration.",
    ["/experiment-fabric"],
  ),
  glossary(
    "champion-model",
    "Champion Model",
    "The currently selected candidate under stated evidence and constraints.",
    ["/algorithm-arena"],
  ),
  glossary(
    "challenger-model",
    "Challenger Model",
    "A candidate compared with a champion under the same experimental conditions.",
    ["/algorithm-arena"],
  ),
];
